services:
  - type: web
    name: gym-backend
    runtime: python
    buildCommand: ""
    startCommand: gunicorn gestion_clients_gym.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: gestion_clients_gym.settings
      - key: SECRET_KEY
        value: TsafNes.19891989
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: railway
          property: connectionString
